% Create a wildcard for looking for the right type of files% Create a wildcard for looking for the right type of files
wildcard = sprintf('%s/experiments/%s/', ...
                   char(java.lang.System.getProperty('user.home')), ...
                   datetime('now', 'Format', 'yyyy'));
% Create a dialog box to load the file
%[filenamelist, pathname] = ...
%    uigetfile({'*m1.spc', 'SPC-files (*m1.spc)'; ...
%               '*.*',     'All Files (*.*)'}, ...
%               'Pick a file', ...
%               'MultiSelect', 'on', ...
%               wildcard);
pathname = uigetdir(wildcard, 'Pick a Directory');
% Find all files with *m*_c*spc.spc in the subdirectories
filenamelist = dir([pathname, filesep, '**', filesep, '*m*_c*.s*']);
filenamelist = strcat({filenamelist.folder}, ...
                      repmat({filesep}, size(filenamelist))', ...
                      {filenamelist.name});
% Find the files that match the SPCM64 naming convention
X = cellfun(@isempty, regexp(filenamelist, 'm\d_c\d\d\.s..'));
% Keep only filenames matching the naming convention
filenamelist = filenamelist(~X);

for i = 1 : numel(filenamelist)
    targetfile = filenamelist{i};
    targetfile(end - 9 : end - 7) = filenamelist{i}(end - 6 : end - 4);
    targetfile(end - 6 : end - 4) = filenamelist{i}(end - 10 : end - 8);
    movefile(filenamelist{i}, targetfile)
end